import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Restaurant from '#models/restaurant'

export default class RestaurantSeeder extends BaseSeeder {
  async run() {
    const restaurants = [
      {
        name: 'Le Cinq',
        michelinStar: 'THREE',
        street: '31 Avenue George V',
        postcode: '75008',
        city: 'Paris',
        country: 'France',
        codePostal: 75008,
        maxPrice: 380,
        cuisine: 'Française',
        lat: 48.8697,
        lng: 2.3017,
      },
      {
        name: 'L\'Arpège',
        michelinStar: 'THREE',
        street: '84 Rue de Varenne',
        postcode: '75007',
        city: 'Paris',
        country: 'France',
        codePostal: 75007,
        maxPrice: 340,
        cuisine: 'Végétarienne',
        lat: 48.8554,
        lng: 2.3163,
      },
      {
        name: 'Septime',
        michelinStar: 'ONE',
        street: '80 Rue de Charonne',
        postcode: '75011',
        city: 'Paris',
        country: 'France',
        codePostal: 75011,
        maxPrice: 120,
        cuisine: 'Bistrot moderne',
        lat: 48.8528,
        lng: 2.3807,
      },
      {
        name: 'Paul Bocuse',
        michelinStar: 'THREE',
        street: '40 Rue de la Plage',
        postcode: '69660',
        city: 'Collonges-au-Mont-d\'Or',
        country: 'France',
        codePostal: 69660,
        maxPrice: 250,
        cuisine: 'Lyonnaise',
        lat: 45.8303,
        lng: 4.8427,
      },
      {
        name: 'Maison Lameloise',
        michelinStar: 'THREE',
        street: '36 Place d\'Armes',
        postcode: '71150',
        city: 'Chagny',
        country: 'France',
        codePostal: 71150,
        maxPrice: 220,
        cuisine: 'Bourguignonne',
        lat: 46.9077,
        lng: 4.7488,
      },
      {
        name: 'Le Bernardin',
        michelinStar: 'TWO',
        street: '155 West 51st Street',
        postcode: '10019',
        city: 'New York',
        country: 'USA',
        codePostal: 10019,
        maxPrice: 290,
        cuisine: 'Fruits de mer',
        lat: 40.7617,
        lng: -73.9828,
      },
      {
        name: 'Bras',
        michelinStar: 'TWO',
        street: 'Route de l\'Aubrac',
        postcode: '12210',
        city: 'Laguiole',
        country: 'France',
        codePostal: 12210,
        maxPrice: 180,
        cuisine: 'Terroir',
        lat: 44.6833,
        lng: 2.8500,
      },
      {
        name: 'Frenchie',
        michelinStar: null,
        street: '5 Rue du Nil',
        postcode: '75002',
        city: 'Paris',
        country: 'France',
        codePostal: 75002,
        maxPrice: 95,
        cuisine: 'Bistrot',
        lat: 48.8634,
        lng: 2.3480,
      },
    ] as const

    for (const restaurant of restaurants) {
      await Restaurant.updateOrCreate({ name: restaurant.name }, restaurant)
    }
  }
}
