/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AdminRestaurants: () => import('#controllers/admin_restaurants_controller'),
  Home: () => import('#controllers/home_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  PourToi: () => import('#controllers/pour_toi_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Restaurants: () => import('#controllers/restaurants_controller'),
  Session: () => import('#controllers/session_controller'),
  Swipe: () => import('#controllers/swipe_controller'),
  AdminRestaurants: () => import('#controllers/admin_restaurants_controller'),
  Search: () => import('#controllers/search_controller'),
  PublicProfiles: () => import('#controllers/public_profiles_controller'),
}
