/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Home: () => import('#controllers/home_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  PourToi: () => import('#controllers/pour_toi_controller'),
  Session: () => import('#controllers/session_controller'),
  Swipe: () => import('#controllers/swipe_controller'),
}
